# Generated by Django 5.2.5 on 2025-09-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_query_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='city',
            field=models.CharField(choices=[('', 'Seleccione una ciudad'), ('LaPlata', 'La Plata'), ('Quilmes', 'Quilmes'), ('CABA', 'CABA'), ('Adrogue', 'Adrogue'), ('FlorencioVarela', 'Florencio Varela')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.CharField(choices=[('', 'Seleccione una ciudad'), ('LaPlata', 'La Plata'), ('Quilmes', 'Quilmes'), ('CABA', 'CABA'), ('Adrogue', 'Adrogue'), ('FlorencioVarela', 'Florencio Varela')], default='', max_length=50),
        ),
    ]
